Horseplay/Models/CompanyGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Horseplay.Models
{
    public class CompanyGroup
    {
        [ScaffoldColumn(false)]
        public int TenantId { get; set; }
        [ScaffoldColumn(false)]
        public int CompanyGroupId { get; set; }
        [Required(ErrorMessage ="Nazwa grupy jest wymagana!")]
        [Display(Name="Nazwa grupy")]       
        public string Name { get; set; }
        [Display(Name="Opis grupy")]
        public string Description { get; set; }

    }
}

Horseplay/Controllers/CompanyGroupController.cs
using Horseplay.DAL;
using Horseplay.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Horseplay.Controllers
{
    public class CompanyGroupController : Controller
    {
        // GET: CompanyGroup
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCompanyGroup(CompanyGroup companyGroup)
        {
            if (!ModelState.IsValid)
            {
                return View("Add",companyGroup);
            }else
            {
                HorseplayContext db = new HorseplayContext();
                if (db.CompanyGroups.Any(x => x.Name == companyGroup.Name))
                {
                    ModelState.AddModelError(string.Empty, "Grupa o takiej nazwie już istnieje!");
                    return View("Add",companyGroup);
                }else
                {
                    db.CompanyGroups.Add(companyGroup);
                    db.SaveChanges();
                    return View("companyGroupCreated",companyGroup);
                }
            }
            
        }
    }
}

Horseplay/Views/CompanyGroup/Add.cshtml
@model Horseplay.Models.CompanyGroup

<body>
    <div>
        @using (Html.BeginForm("AddCompanyGroup", "CompanyGroup"))
        {
            @Html.ValidationSummary(true)
            @Html.EditorFor(m => m, new { htmlAttributes = new { @class = "form-control" }, })
            <input type="submit" value="Zapisz" class="btn btn-success" />
        }
    </div>
</body>

Horseplay/Views/CompanyGroup/companyGroupCreated.cshtml
@model Horseplay.Models.CompanyGroup

@{
    ViewBag.Title = "companyGroupCreated";
}

<h2>Gratulacje! Grupa @Model.Name została pomyślnie utworzona!</h2>