Horseplay/Controllers/HRController.cs
using Horseplay.DAL;
using Horseplay.Models;
using Horseplay.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Horseplay.Controllers
{
    public class HRController : Controller
    {
        // GET: HR
        public ActionResult Index()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }

        public ActionResult GetEmployeeGroups()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                int tenantId = (int)Session["TenantId"];
                HorseplayContext db = new HorseplayContext();
                var employeeGroups = db.EmployeeGroups.Where(eg => eg.TenantId == tenantId);
                return View(employeeGroups);
            }
        }

        public ActionResult CreateEmployeeGroup()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]

        public ActionResult CreateEmployeeGroup(EmployeeGroup eg)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateEmployeeGroup", eg);
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                if (db.EmployeeGroups.Any(x => x.Name == eg.Name && x.TenantId==tenantId))
                {
                    ModelState.AddModelError(string.Empty, "Grupa o takiej nazwie już istnieje. Podaj unikatową nazwę grupy");
                    return View("CreateEmployeeGroup", eg);
                }
                else
                {
                    eg.addedBy = (int)Session["UserId"];
                    eg.dateAdded = DateTime.Now;
                    eg.TenantId = tenantId;
                    db.EmployeeGroups.Add(eg);
                    db.SaveChanges();
                    return RedirectToAction("GetEmployeeGroups");
                }
            }

        }
        
        public ActionResult EmployeeGroupDetails(int id)
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                var egs = db.EmployeeGroups.Where(e => e.EmployeeGroupId == id && e.TenantId == tenantId);
                if (egs.Any())
                {
                    return View(egs.FirstOrDefault());
                }
                else
                {
                    return new HttpNotFoundResult("Nie znaleziono strony");
                }
            }
        }

        public ActionResult EditEmployeeGroup(int id)
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                var egs = db.EmployeeGroups.Where(e => e.EmployeeGroupId == id && e.TenantId == tenantId);
                if (egs.Any())
                {
                    return View(egs.FirstOrDefault());
                }
                else
                {
                    return new HttpNotFoundResult("Nie znaleziono strony");
                }
            }
        }

        [HttpPost]
        public ActionResult EditEmployeeGroup(EmployeeGroup eg)
        {
            if (!ModelState.IsValid)
            {
                return View("EditEmployeeGroup", eg);
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                int userId = (int)Session["UserId"];
                if (db.EmployeeGroups.Any(x => x.Name == eg.Name && x.TenantId==tenantId && x.EmployeeGroupId!=eg.EmployeeGroupId))
                {
                    ModelState.AddModelError(string.Empty, "Grupa o takiej nazwie już istnieje. Podaj unikatową nazwę grupy");
                    return View("EditEmployeeGroup", eg);
                }
                else
                {
                    var oldEg = db.EmployeeGroups.FirstOrDefault(e => e.EmployeeGroupId == eg.EmployeeGroupId && e.TenantId == tenantId);
                    if (oldEg == null)
                    {
                        return new HttpNotFoundResult("Wystąpił nieoczekiwany błąd");
                    }else
                    {
                        oldEg.Name = eg.Name;
                        oldEg.dateModified = DateTime.Now;
                        oldEg.modifiedBy = userId;
                        db.Entry(oldEg).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("GetEmployeeGroups");
                    }  
                }
            }
        }

        public ActionResult DeleteEmployeeGroup(int id)
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                var egs = db.EmployeeGroups.Where(e => e.EmployeeGroupId == id && e.TenantId == tenantId);
                if (egs.Any())
                {
                    return View(egs.FirstOrDefault());
                }
                else
                {
                    return new HttpNotFoundResult("Nie znaleziono strony");
                }
            }
        }

        [HttpPost]
        public ActionResult DeleteEmployeeGroup(EmployeeGroup eg)
        {
            HorseplayContext db = new HorseplayContext();
            int tenantId = (int)Session["TenantId"];
            var oldEg = db.EmployeeGroups.FirstOrDefault(e => e.EmployeeGroupId == eg.EmployeeGroupId && e.TenantId == tenantId);
            if (oldEg == null)
            {
                return new HttpNotFoundResult("Wystąpił nieoczekiwany błąd");
            }
            else
            {
                db.EmployeeGroups.Remove(oldEg);
                db.SaveChanges();
                return RedirectToAction("GetEmployeeGroups");
            }
        }

        public ActionResult GetEmployees()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                var employees = db.Employees.Include("Groups").Where(e => e.TenantId == tenantId);

                return View(employees);
            }
        }

        public ActionResult CreateEmployee()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                HRCreateEmployeeViewModel vm = new HRCreateEmployeeViewModel();
                int tenantId = (int)Session["TenantId"];
                vm.employeeGroups = db.EmployeeGroups.Where(eg => eg.TenantId == tenantId);
                return View(vm);
            }
        }

        [HttpPost]
        public ActionResult CreateEmployee(HRCreateEmployeeViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateEmployee",vm);
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                vm.employee.TenantId = (int)Session["TenantId"];
                vm.employee.addedBy = (int)Session["UserId"];
                vm.employee.dateAdded = DateTime.Now;
                List<EmployeeGroup> groups = new List<EmployeeGroup>();
                if (vm.selectedGroups != null)
                {
                    foreach (int i in vm.selectedGroups)
                    {
                        var result = (from eg in db.EmployeeGroups
                                      where eg.EmployeeGroupId == i
                                      select eg);
                        foreach (var emp in result)
                        {
                            groups.Add(emp);
                        }
                    }
                }
                
                if (groups.Any())
                {
                    vm.employee.Groups = groups;
                }

Horseplay/Views/HR/CreateEmployee.cshtml
@model Horseplay.ViewModels.HRCreateEmployeeViewModel
@using Horseplay.Static

    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="my-row">
                @Html.LabelFor(model => model.employee.Name, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.Surname, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Surname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Surname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.Country, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.DropDownListFor(model => model.employee.Country,Model.Countries(0), new { @class = "form-control", id="dd-country", data_placeholder = "Wybierz.." })
                    @Html.ValidationMessageFor(model => model.employee.Country, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.EmployeeGroupId, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @*@Html.DropDownListFor(x => Model.selectedGroups, Model.employeeGroups, "Wybierz", new { @class = "form-control", id="employeeGroup" })*@
                    @Html.ListBoxFor(x => Model.selectedGroups,new MultiSelectList(Model.employeeGroups, "EmployeeGroupId", "Name"), new { @class = "form-control", id = "employeeGroup", multiple="multiple", data_placeholder="Wybierz grupy.." })
                </div>
                @{
                    string str = "";
                    if (!Model.employeeGroups.Any())
                    {
                        HtmlString al = Html.ActionLink("dodaj grupę", "CreateEmployeeGroup", "HR");
                        str = "Wygląda na to, że nie dodałeś jeszcze żadnej grupy pracowników.</br>Warto " + al + ", pozwoli Ci to zachować większy porządek grupując pracowników o tych samych obowiązkach razem!";
                    }
                    else
                    {
                        HtmlString al = Html.ActionLink("tutaj", "GetEmployeeGroups", "HR");
                        str = "Wybierz grupę pracowników z rozwijanej listy obok.</br>Jeśli potrzebujesz dodać nową grupę lub zmienić dane istniejącej, możesz zrobić to " + al + ".";
                    }
                    @CustomHelper.CreatePrompter(str, "green");
                }
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.BirthDay, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.TextBoxFor(model=>model.employee.BirthDay, new { @class = "form-control", @type = "date" })
                    @Html.ValidationMessageFor(model => model.employee.BirthDay, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.EmployedOn, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.TextBoxFor(model => model.employee.EmployedOn, new { @class = "form-control", @type="date" })
                    @Html.ValidationMessageFor(model => model.employee.EmployedOn, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.PersonalIdentityNumber, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.TextBoxFor(model => model.employee.PersonalIdentityNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.employee.PersonalIdentityNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.IdNumber, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.TextBoxFor(model => model.employee.IdNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.employee.IdNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.ContractType, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.DropDownListFor(model => model.employee.ContractType, Model.ContractTypes(0), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.employee.ContractType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.ExpirationDate, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.TextBoxFor(model => model.employee.ExpirationDate, new { @class = "form-control", @type = "date" })
                    @Html.ValidationMessageFor(model => model.employee.ExpirationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.Phone, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.Mobile, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.Mail, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Mail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Mail, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.Address, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Utwórz" class="btn btn-default" />
                    </div>
                </div>
            </div>
    }
    
    <div>
        @Html.ActionLink("Powrót do listy pracowników", "GetEmployees")
    </div>

@section scripts{
    <script>
        $(function () {
            $('#employeeGroup').chosen({ width: '100%', no_results_text: "Brak wyników dla.." });
            $('#dd-country').chosen({ width: '100%', no_results_text: "Brak wyników dla.." });
        });
    </script>
    }

Horseplay/Views/HR/CreateEmployeeGroup.cshtml
@model Horseplay.Models.EmployeeGroup

    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Utwórz" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Powrót do listy grup pracowników", "GetEmployeeGroups")
    </div>

Horseplay/Views/HR/DeleteEmployeeGroup.cshtml
@model Horseplay.Models.EmployeeGroup


<h3>Czy na pewno chcesz usunąć tę grupę?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    
    </dl>
    
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.EmployeeGroupId)
        @Html.AntiForgeryToken()
    
        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-danger" /> |
            @Html.ActionLink("Powrót do listy grup pracowników", "GetEmployeeGroups")
        </div>
    }
</div>

Horseplay/Views/HR/EditEmployee.cshtml
@model Horseplay.ViewModels.HRCreateEmployeeViewModel
@using Horseplay.Static

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        
            <h4>Edycja pracownika</h4>
            <div>
                @Html.HiddenFor(model => model.employee.EmployeeId)
            </div>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="my-row">
                @Html.LabelFor(model => model.employee.Name, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.Surname, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Surname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Surname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.Country, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.DropDownListFor(model => model.employee.Country, Model.Countries(0), new { @class = "form-control", id="dd-country", data_placeholder = "Wybierz.." })
                    @Html.ValidationMessageFor(model => model.employee.Country, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.EmployeeGroupId, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.ListBoxFor(x => Model.selectedGroups, new MultiSelectList(Model.employeeGroups, "EmployeeGroupId","Name"), new { @class = "form-control", id = "employeeGroup", multiple = "multiple", data_placeholder = "Wybierz grupy.." })
                    @Html.ValidationMessageFor(model => model.employee.EmployeeGroupId, "", new { @class = "text-danger" })
                </div>
                @{
                    string str = "";
                    if (!Model.employeeGroups.Any())
                    {
                        HtmlString al = Html.ActionLink("dodaj grupę", "CreateEmployeeGroup", "HR");
                        str = "Wygląda na to, że nie dodałeś jeszcze żadnej grupy pracowników.</br>Warto " + al + ", pozwoli Ci to zachować większy porządek grupując pracowników o tych samych obowiązkach razem!";
                    }
                    else
                    {
                        HtmlString al = Html.ActionLink("tutaj", "GetEmployeeGroups", "HR");
                        str = "Wybierz grupę pracowników z rozwijanej listy obok.</br>Jeśli potrzebujesz dodać nową grupę lub zmienić dane istniejącej, możesz zrobić to " + al + ".";
                    }
                    @CustomHelper.CreatePrompter(str, "green");
                }
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.BirthDay, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.BirthDay, new { htmlAttributes = new { @class = "form-control", @type="date" } })
                    @Html.ValidationMessageFor(model => model.employee.BirthDay, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.EmployedOn, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.EmployedOn, new { htmlAttributes = new { @class = "form-control", @type="date" } })
                    @Html.ValidationMessageFor(model => model.employee.EmployedOn, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.PersonalIdentityNumber, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.TextBoxFor(model => model.employee.PersonalIdentityNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.employee.PersonalIdentityNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.IdNumber, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.TextBoxFor(model => model.employee.IdNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.employee.IdNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.ContractType, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.DropDownListFor(model => model.employee.ContractType, Model.ContractTypes(0), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.employee.ContractType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.ExpirationDate, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.TextBoxFor(model => model.employee.ExpirationDate, new { @class = "form-control", @type = "date" })
                    @Html.ValidationMessageFor(model => model.employee.ExpirationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.employee.Phone, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.Mobile, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.Mail, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Mail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Mail, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="my-row">
                @Html.LabelFor(model => model.employee.Address, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.employee.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.employee.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Zapisz" class="btn btn-default" />
                    </div>
                </div>
            </div>
    }

    <div>
        @Html.ActionLink("Powrót do listy pracowników", "GetEmployees")
    </div>

@section scripts{
    <script>
        $(function () {
            $('#employeeGroup').chosen({ width: '100%', no_results_text: "Brak wyników dla.." });
            $('#dd-country').chosen({ width: '100%', no_results_text: "Brak wyników dla.." });
        });
    </script>
    }

Horseplay/Views/HR/EditEmployeeGroup.cshtml
@model Horseplay.Models.EmployeeGroup


<br />
<br />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.HiddenFor(model=>model.EmployeeGroupId)
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Zapisz" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Powrót do listy grup pracowników", "GetEmployeeGroups")
    </div>

Horseplay/Views/HR/Index.cshtml
@using Horseplay.Static

<br />

@{
    HtmlString al = Html.ActionLink("to zrobić", "CreateEmployee", "HR");
    string str = "Ten panel służy do zarządania informacjami o pracownikach. Portal jest ciągle rozwijany i obecna funkcjonalność różni się od ostatecznej funkcjonalności...<br><br>Jeśli jeszcze nie dodałeś żadnego pracownika, warto " + al;
    al = Html.ActionLink("zleceniu transportowym", "CreateTransportOrder", "Logistics");
    str += ", aby np. przypisać go jako kierowcę w " + al;
    al = Html.ActionLink("grupę pracowniczą!", "CreateEmployeeGroup", "HR");
    str += ". Warto również połączyć wszystkich pracowników pełniących podobne obowiązki i utworzyć dla nich " + al;
    al = Html.ActionLink("tutaj", "GetEmployees", "HR");
    str += "<br>Jeśli chcesz wyświetlić listę wszystkich dodanych pracowników, możesz zrobić to " + al;
    @CustomHelper.CreateGreeter(str, "green");
}

<br />