Horseplay/Controllers/LogisticsController.cs
using Horseplay.DAL;
using Horseplay.Models;
using Horseplay.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Horseplay.Controllers
{
    public class LogisticsController : Controller
    {
        // GET: Logistics
        public ActionResult Index()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }

        public ActionResult CreateTransportOrder()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                TransportOrderViewModel vm = new TransportOrderViewModel();
                vm = FillTransportOrderViewModel(vm);
                return View(vm);
            }
        }

        [HttpPost]
        public ActionResult CreateTransportOrder(TransportOrderViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                vm = FillTransportOrderViewModel(vm);
                return View("CreateTransportOrder", vm);
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                vm.Rebuild(db);
                if (vm.TransportOrder.Route.Stops.Any())
                {
                    int userId = (int)Session["UserId"];
                    int tenantId = (int)Session["TenantId"];
                    int order = 0;
                    //if there are any stops, let's create them
                    List<RouteStop> stops = new List<RouteStop>();
                    foreach (var stop in vm.TransportOrder.Route.Stops)
                    {
                        Address address = new Address();
                        address.Name = stop.Address.Name;
                        address.Street = stop.Address.Street;
                        address.ZipCode = stop.Address.ZipCode;
                        address.City = stop.Address.City;
                        address.Country = stop.Address.Country;
                        address.AddedBy = userId;
                        address.TenantId = tenantId;
                        address.DateAdded = DateTime.Now;
                        RouteStop rs = new RouteStop();
                        rs.Address = address;
                        rs.AddedBy = userId;
                        rs.DepartureDate = stop.DepartureDate;
                        rs.ArrivalDate = stop.ArrivalDate;
                        rs.StopType = stop.StopType;
                        rs.TenantId = tenantId;
                        rs.DateAdded = DateTime.Now;
                        rs.Order = order;
                        stops.Add(rs);
                        order++;
                    }
                    Route Route = new Route() { AddedBy = userId, TenantId = tenantId, DateAdded = DateTime.Now, Length=vm.TransportOrder.Route.Length, Stops = stops };
                    TransportOrder to = new TransportOrder() { AddedBy = userId, DateAdded = DateTime.Now, TenantId = tenantId, Type = vm.TransportOrder.Type, Route = Route, Cost=vm.TransportOrder.Cost, Truck=vm.IntToVehicle(vm.SelectedTruck), Trailer=vm.IntToVehicle(vm.SelectedTrailer), PrimaryDriver=vm.IntToEmployee(vm.SelectedPrimaryDriver), SecondaryDriver=vm.IntToEmployee(vm.SelectedSecondaryDriver), Remarks=vm.TransportOrder.Remarks, Carrier=vm.IntToCarrier(vm.SelectedCarrier), Customer=vm.IntToCustomer(vm.SelectedCustomer) };
                    db.TransportOrders.Add(to);
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (DbEntityValidationException e)
                    {
                        foreach (var error in e.EntityValidationErrors)
                        {
                            foreach (var propertyError in error.ValidationErrors)
                            {
                                Console.WriteLine($"{propertyError.PropertyName} had the following issue: {propertyError.ErrorMessage}");
                            }
                        }
                    }

                }
                return RedirectToAction("GetTransportOrders");
            }

        }

        public ActionResult GetTransportOrders()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                int tenantId = (int)Session["TenantId"];
                HorseplayContext db = new HorseplayContext();
                var tos = db.TransportOrders
                            .Include(to => to.Truck)
                            .Include(to => to.Trailer)
                            .Include(to => to.PrimaryDriver)
                            .Include(to => to.SecondaryDriver)
                            .Include(to => to.Carrier)
                            .Include(to => to.Carrier.Address)
                            .Include(to => to.Customer)
                            .Include(to => to.Route.Stops.Select(s => s.Address))
                            .Where(t => t.TenantId == tenantId).OrderByDescending(t => t.DateAdded);
                return View(tos);
            }
 
        }

        public ActionResult TransportOrderDetails(int id)
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                var tos = db.TransportOrders
                            .Include(to => to.Truck)
                            .Include(to => to.Trailer)
                            .Include(to => to.PrimaryDriver)
                            .Include(to => to.SecondaryDriver)
                            .Include(to => to.Carrier)
                            .Include(to => to.Customer)
                            .Include(to => to.Route.Stops.Select(s => s.Address))
                            .Where(t => t.TenantId == tenantId && t.TransportOrderId == id);
                if (tos.Any())
                {
                    return View(tos.FirstOrDefault());

                }
                else
                {
                    return new HttpNotFoundResult("Nie znaleziono strony");
                }
            }
        }

        public ActionResult DeleteTransportOrder(int id)
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                var tos = db.TransportOrders
                            .Include(to => to.Truck)
                            .Include(to => to.Trailer)
                            .Include(to => to.PrimaryDriver)
                            .Include(to => to.SecondaryDriver)
                            .Include(to => to.Carrier)
                            .Include(to => to.Customer)
                            .Include(to => to.Route.Stops.Select(s => s.Address))
                            .Where(t => t.TenantId == tenantId && t.TransportOrderId == id);
                if (tos.Any())
                {
                    return View(tos.FirstOrDefault());

                }
                else
                {
                    return new HttpNotFoundResult("Nie znaleziono strony");
                }
            }
        }
        [HttpPost]
        public ActionResult DeleteTransportOrder(TransportOrder to)
        {
            HorseplayContext db = new HorseplayContext();
            int tenantId = (int)Session["Tenantid"];
            var tos = db.TransportOrders
                        .Include(x => x.Route)
                        .Include(x=>x.Route.Stops)
                        .Include(x => x.Route.Stops.Select(s => s.Address))
                        .Where(x => x.TransportOrderId == to.TransportOrderId && x.TenantId == tenantId);
            if (tos.Any())
            {
                TransportOrder oldTo = tos.FirstOrDefault();
                DeleteDependentRoute(oldTo, db);
                db.TransportOrders.Remove(oldTo);
                db.SaveChanges();
                return RedirectToAction("GetTransportOrders");
            }
            else
            {
                return new HttpNotFoundResult("Nieoczekiwany błąd");
            }
        }

        public ActionResult EditTransportOrder(int id)
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                TransportOrderViewModel vm = new TransportOrderViewModel();
                vm = FillTransportOrderViewModel(vm, id);
                return View(vm);
            }

Horseplay/Views/Logistics/CreateVehicle.cshtml
@model Horseplay.ViewModels.VehicleViewModel
@using Horseplay.Static

<br />
<br />
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Tworzenie pojazdu</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.Plate, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.Vehicle.Plate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vehicle.Plate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.Type, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.DropDownListFor(model => model.Vehicle.Type, Model.VehicleTypes(0), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Vehicle.Type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.Brand, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.Vehicle.Brand, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vehicle.Brand, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.Model, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.Vehicle.Model, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vehicle.Model, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.ProductionYear, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.Vehicle.ProductionYear, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vehicle.ProductionYear, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.Vin, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.Vehicle.Vin, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vehicle.Vin, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.Capacity, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.Vehicle.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vehicle.Capacity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.RegistrationDate, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.TextBoxFor(model => model.Vehicle.RegistrationDate, new { @class = "form-control", @type = "date" })
                    @Html.ValidationMessageFor(model => model.Vehicle.RegistrationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.ServiceDate, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.TextBoxFor(model => model.Vehicle.ServiceDate, new { @class = "form-control", @type = "date" })
                    @Html.ValidationMessageFor(model => model.Vehicle.ServiceDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.DefaultUser, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.DropDownListFor(model => model.SelectedUser, new SelectList(Model.Employees, "EmployeeId", "FullName"), "Wybierz", new { @class = "form-control", id = "dd-primary-driver" })
                    @Html.ValidationMessageFor(model => model.Vehicle.DefaultUser, "", new { @class = "text-danger" })
                </div>
                @{
                    string str = "";
                    if (!Model.Employees.Any())
                    {
                        HtmlString al = Html.ActionLink("dodaj pracownika", "CreateEmployee", "HR");
                        str = "Wygląda na to, że nie dodałeś jeszcze żadnego pracownika, którego mógłbyś przypisać jako domyślnego użytkownika.</br>Najpierw " + al + " a on pojawi się tutaj po odświeżeniu strony!";
                    }
                    else
                    {
                        HtmlString al = Html.ActionLink("tutaj", "GetEmployees", "HR");
                        str = "Wybierz pracownika z rozwijanej listy obok.</br>Jeśli potrzebujesz dodać pracownika lub zmienić jego dane, możesz zrobić to " + al + ".";
                    }
                    @CustomHelper.CreatePrompter(str, "purple");
                }
            </div>
            
            <div class="my-row">
                @Html.LabelFor(model => model.Vehicle.Description, htmlAttributes: new { @class = "control-label my-label" })
                <div class="my-input">
                    @Html.EditorFor(model => model.Vehicle.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vehicle.Description, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Utwórz" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Powrót do listy pojazdów", "GetVehicles")
    </div>

Horseplay/Views/Logistics/GetTransportOrders.cshtml
@model IEnumerable<Horseplay.Models.TransportOrder>
@using Horseplay.Static

<link href="~/Content/table-handler.css" rel="stylesheet" />

    <br />
    <br />
    @if (Model != null && Model.Any())
    {
        @Html.ActionLink("Dodaj zlecenie transportowe", "CreateTransportOrder");
    }
    else
    {
        <table class="info-table table-purple">
            <tr>
                <th><div class="info-header"><div class="small-circle circle-purple">?</div><p class="purple">Wskazówka</p></div></th>
            </tr>
            <tr>
                <td>
                    <p>Na razie nie dodałeś jeszcze żadnych zleceń transportowych. @Html.ActionLink("Dodaj zlecenie transportowe", "CreateTransportOrder") </p>
                </td>
            </tr>
        </table>

    }

    <br/>
    <br/>
    <section id="no-more-tables">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Type)
                    </th>
                    <th>
                        @Html.Label("Przewoźnik/pojazd")
                    </th>
                    <th>
                        @Html.Label("Długość [km]")
                    </th>
                    <th>
                        @Html.Label("Route", "Trasa")
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if(Model != null && Model.Any())
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td data-title="@Html.DisplayNameFor(model => model.Type)">
                                <p>@Utilities.EnumString(new Horseplay.Models.TransportType(),(int)item.Type)</p>
                            </td>
                            <td data-title="Przewoźnik/pojazd">
                                @{ 
                                    if (item.Type == 0)
                                    {
                                        if (item.PrimaryDriver != null)
                                        {
                                            <p>Kierowca:@if (item.PrimaryDriver != null)
                                            {
                                                @Html.ActionLink(item.PrimaryDriver.FullName, "EmployeeDetails", "HR", new { id = item.PrimaryDriver.EmployeeId }, null)
                                            }</p>
                                            <br />
                                        }
                                        if (item.SecondaryDriver != null)
                                        {
                                            <p>Kierowca 2: @if (item.SecondaryDriver != null)
                                            {
                                                @Html.ActionLink(item.SecondaryDriver.FullName, "EmployeeDetails", "HR", new { id = item.SecondaryDriver.EmployeeId }, null)
                                            }</p>
                                            <br />
                                        }
                                        if (item.Truck != null)
                                        {
                                            <p>Ciągnik: @if (item.Truck != null)
                                            {
                                                @Html.ActionLink(item.Truck.Plate, "VehicleDetails", "Logistics", new { id = item.Truck.VehicleId }, null)
                                            }</p>
                                        }
                                        if(item.Trailer != null)
                                        {
                                            <b>/</b>
                                            <p>Naczepa: @if (item.Trailer != null)
                                            {
                                                @Html.ActionLink(item.Trailer.Plate, "VehicleDetails", "Logistics", new { id = item.Trailer.VehicleId }, null)
                                            }</p>
                                        }
                                    }
                                    else if ((int)item.Type == 1)
                                    {
                                        if (item.Carrier != null)
                                        {
                                            <p>
                                                @Html.ActionLink(item.Carrier.Name, "CompanyDetails", "CRM", new { id = item.Carrier.CompanyId }, null)
                                            </p>
                                                <br />
                                        }
                                    }
                                }
                            </td>
                            <td data-title="Długość [km]">
                                <p> @Html.DisplayFor(model=> item.Route.Length)</p>
                            </td>
                            <td data-title="Trasa">
                                <table class="table">
                                    <tbody>
                                        @foreach (var stop in item.Route.Stops)
                                        {
                                            <tr>
                                                <td data-title="Miejsce"> @Html.DisplayFor(x => stop.Address.FullName)</td>
                                                <td data-title="Typ"> @Utilities.EnumString(new Horseplay.Models.StopType(), (int)stop.StopType)</td>
                                                <td data-title="Data"> @Html.DisplayFor(x => stop.ArrivalDateShort)</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </td>
                            <td>
                                @Html.ActionLink("Edytuj", "EditTransportOrder", new { id = item.TransportOrderId }) |
                                @Html.ActionLink("Szczegóły", "TransportOrderDetails", new { id = item.TransportOrderId }) |
                                @Html.ActionLink("Usuń", "DeleteTransportOrder", new { id = item.TransportOrderId })
                                @Html.ActionLink("Raport", "GenerateRouteReport", "Report", new { id= item.TransportOrderId },null)
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </section>

Horseplay/Views/Logistics/Index.cshtml
@using Horseplay.Static

<br />

@{
    HtmlString al = Html.ActionLink("Dodaj informacje", "CreateVehicle", "Logistics");
    string str = "Ten panel służy do zarządania logistyką firmy. Portal jest ciągle rozwijany i obecna funkcjonalność różni się od ostatecznej funkcjonalności...<br><br>" + al;
    al = Html.ActionLink("zleceń transportowych", "CreateTransportOrder", "Logistics");
    str += " o wszystkich pojazdach Twojej firmy, aby np. przypisywać je do tworzonych " + al;
    al = Html.ActionLink("zlecenia transportowe", "CreateTransportOrder", "Logistics");
    str += ".<br>Zarządzaj informacją o tym, co robi Twoja flota, tworząc " + al;
    al = Html.ActionLink("tutaj", "GetTransportOrders", "Logistics");
    str += "<br>Jeśli chcesz wyświetlić listę dodanych zleceń transportowych, możesz to zrobić " + al;
    @CustomHelper.CreateGreeter(str, "purple");
}

<br />

Horseplay/Views/Logistics/TransportOrderDetails.cshtml
@model Horseplay.Models.TransportOrder
@using Horseplay.Static

<link href="~/Content/table-handler.css" rel="stylesheet" />

    <div>
        <h4>Szczegóły zlecenia transportowego</h4>
        <hr />
        <div>
            <dl class="dl-horizontal">  
                <dt>
                    @Html.DisplayNameFor(model => model.Type)
                </dt>
    
                <dd>
                    <p>@Utilities.EnumString(new Horseplay.Models.TransportType(), (int)Model.Type)</p>
                </dd>
                @if ((int)Model.Type == 0)
                {
                    <dt>
                        @Html.DisplayNameFor(model => model.PrimaryDriver)
                    </dt>
                    <dd>
                        @if (Model.PrimaryDriver != null)
                        {
                            @Html.ActionLink(Model.PrimaryDriver.FullName, "EmployeeDetails", "HR", new { id = Model.PrimaryDriver.EmployeeId }, null)
                        }
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.SecondaryDriver)
                    </dt>
                    <dd>
                        @if (Model.SecondaryDriver != null)
                        {
                            @Html.ActionLink(Model.SecondaryDriver.FullName, "EmployeeDetails", "HR", new { id = Model.SecondaryDriver.EmployeeId }, null)
                        }
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Truck)
                    </dt>
                    <dd>
                        @if (Model.Truck != null)
                        {
                            @Html.ActionLink(Model.Truck.Plate, "VehicleDetails", "Logistics", new { id = Model.Truck.VehicleId }, null)
                        }
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Trailer)
                    </dt>
                    <dd>
                        @if (Model.Trailer != null)
                        {
                            @Html.ActionLink(Model.Trailer.Plate, "VehicleDetails", "Logistics", new { id = Model.Trailer.VehicleId }, null)
                        }
                    </dd>
                }
                else if ((int)Model.Type == 1)
                {
                    <dt>
                        @Html.DisplayNameFor(model => model.Carrier)
                    </dt>
                    <dd>
                        @if (Model.Carrier != null)
                        {
                            @Html.ActionLink(Model.Carrier.FullName, "CompanyDetails", "CRM", new { id = Model.Carrier.CompanyId }, null)
                        }
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Cost)
                    </dt>
                    <dd>
                        <p>@Html.DisplayFor(model=>model.Cost)</p>
                    </dd>
                }

                <dt>
                    @Html.DisplayNameFor(model => model.Route.Length)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Route.Length)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Remarks)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Remarks)
                </dd>
                <dt>
                    @Html.LabelFor(model => model.DateAdded, "Utworzono")
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.DateAdded) przez użytkownika @Utilities.UserName((int)Model.AddedBy)
                </dd>
                @if (Model.DateModified != null)
                {
                    <dt>
                        @Html.LabelFor(model => model.DateModified, "Zmodyfikowano")
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.DateModified) przez użytkownika @Utilities.UserName((int)Model.ModifiedBy)
                    </dd>
                }
            </dl>
        </div>
        <br />
        <section id="no-more-tables">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.Label("Miejsce")
                        </th>
                        <th>
                            @Html.Label("Data przyjazdu")
                        </th>
                        <td>
                            @Html.Label("Data wyjazdu")
                        </td>
                        <td>
                            @Html.Label("Typ")
                        </td>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var stop in Model.Route.Stops)
                    {
                        <tr>
                            <td data-title="Miejsce">
                                @stop.Address.FullName
                            </td>
                            <td data-title="Data przyjazdu">
                                @stop.ArrivalDateShort
                            </td>
                            <td data-title="Data wyjazdu">
                                @stop.DepartureDateShort
                            </td>
                            <td data-title="Typ">
                                @Utilities.EnumString(new Horseplay.Models.StopType(), (int)stop.StopType)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </section>
    </div>
    <p>
        @Html.ActionLink("Edytuj", "EditTransportOrder", new { id = Model.TransportOrderId }) |
        @Html.ActionLink("Powrót do listy zleceń transportowych", "GetTransportOrders")
    </p>