Horseplay/Controllers/CRMController.cs
using Horseplay.DAL;
using Horseplay.Models;
using Horseplay.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Horseplay.Controllers
{
    public class CRMController : Controller
    {
        // GET: CRM
        public ActionResult Index()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }

        public ActionResult CreateCompany()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                CompanyViewModel vm = new CompanyViewModel();
                int tenantId = (int)Session["TenantId"];
                return View(vm);
            }
        }

        [HttpPost]
        public ActionResult CreateCompany(CompanyViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateCompany", vm);
            }else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                int userId = (int)Session["UserId"];
                vm.Company.TenantId = tenantId;
                vm.Company.AddedBy = userId;
                vm.Company.DateAdded = DateTime.Now;
                if (vm.Company.Address != null)
                {
                    Address Address = new Address();
                    Address.AddedBy = userId;
                    Address.TenantId = tenantId;
                    Address.DateAdded = DateTime.Now;
                    Address.Name = vm.Company.Address.Name;
                    Address.Street = vm.Company.Address.Street;
                    Address.ZipCode = vm.Company.Address.ZipCode;
                    Address.City = vm.Company.Address.City;
                    Address.Country = vm.Company.Address.Country;
                    vm.Company.Address = Address;
                }
                if (vm.Company.ContactDetail != null)
                {
                    ContactDetail CD = new ContactDetail()
                    {
                        AddedBy = userId,
                        DateAdded = DateTime.Now,
                        TenantId = tenantId,
                        Phone = vm.Company.ContactDetail.Phone,
                        Mobile = vm.Company.ContactDetail.Mobile,
                        PrivatePhone = vm.Company.ContactDetail.PrivatePhone,
                        Fax = vm.Company.ContactDetail.Fax,
                        Mail = vm.Company.ContactDetail.Mail,
                        PrivateMail = vm.Company.ContactDetail.PrivateMail
                    };
                    vm.Company.ContactDetail = CD;
                }
                Company Company = new Company()
                {
                    AddedBy = userId,
                    DateAdded = DateTime.Now,
                    TenantId = tenantId,
                    Type = vm.Company.Type,
                    BusinessRegisterNumber = vm.Company.BusinessRegisterNumber,
                    CourtRegisterNumber = vm.Company.CourtRegisterNumber,
                    TaxRegisterNumber = vm.Company.TaxRegisterNumber,
                    PaymentTerm = vm.Company.PaymentTerm,
                    Address = vm.Company.Address,
                    ContactDetail = vm.Company.ContactDetail
                    
                };
                db.Companies.Add(vm.Company);
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var error in e.EntityValidationErrors)
                    {
                        foreach (var propertyError in error.ValidationErrors)
                        {
                            Console.WriteLine($"{propertyError.PropertyName} had the following issue: {propertyError.ErrorMessage}");
                        }
                    }
                }
                return RedirectToAction("GetCompanies");
            }   
        }

        public ActionResult GetCompanies()
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                var comps = db.Companies
                    .Include(c => c.Address)
                    .Include(c => c.ContactDetail)
                    .Where(c => c.TenantId == tenantId);
                return View(comps);
            }
        }

        public ActionResult CompanyDetails(int id)
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                var comp = db.Companies
                    .Include(c => c.Address)
                    .Include(c => c.ContactDetail)
                    .Where(c => c.TenantId == tenantId && c.CompanyId == id);
                if (comp.Any())
                {
                    return View(comp.FirstOrDefault());
                }
                else
                {
                    return new HttpNotFoundResult("Nie znaleziono strony");
                }
            }   
        }

        public ActionResult DeleteCompany(int id)
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                var comps = db.Companies
                    .Include(c => c.Address)
                    .Include(c => c.ContactDetail)
                    .Where(c => c.TenantId == tenantId && c.CompanyId == id);
                if (comps.Any())
                {
                    return View(comps.FirstOrDefault());
                }
                else
                {
                    return new HttpNotFoundResult("Nie znaleziono strony");
                }
            }
        }

        [HttpPost]
        public ActionResult DeleteCompany(Company comp)
        {
            HorseplayContext db = new HorseplayContext();
            int tenantId = (int)Session["TenantId"];
            var comps = db.Companies
                .Include(c => c.Address)
                .Include(c => c.ContactDetail)
                .Where(c => c.TenantId == tenantId && c.CompanyId == comp.CompanyId);
            if (comps.Any())
            {
                Company oldComp = comps.FirstOrDefault();
                Address oldAddress = db.Addresses.Where(a => a.AddressId == oldComp.Address.AddressId).FirstOrDefault();
                ContactDetail oldCD = db.ContactDetails.Where(a => a.ContactDetailId == oldComp.ContactDetail.ContactDetailId).FirstOrDefault();
                db.Addresses.Remove(oldAddress);
                db.SaveChanges();
                db.ContactDetails.Remove(oldCD);
                db.SaveChanges();
                //db.Companies.Remove(oldComp);
                //db.SaveChanges();
                return View("GetCompanies");
            }
            else
            {
                return new HttpNotFoundResult("Nieoczekiwany błąd");
            }
        }

        public ActionResult EditCompany(int id)
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HorseplayContext db = new HorseplayContext();
                int tenantId = (int)Session["TenantId"];
                var comps = db.Companies
                    .Include(c => c.Address)
                    .Include(c => c.ContactDetail)
                    .Where(c => c.CompanyId == id && c.TenantId == tenantId);

                if (comps.Any())
                {
                    CompanyViewModel vm = new CompanyViewModel();
                    vm.Company = comps.FirstOrDefault();
                    return View(vm);
                }
                else
                {
                    return new HttpNotFoundResult("Nieoczekiwany błąd");
                }
            }
        }

        [HttpPost]

        public ActionResult EditCompany(CompanyViewModel vm)
        {
            if (Session["TenantId"] == null)
            {
                TempData["Info"] = "Nastąpiło automatyczne wylogowanie. Proszę ponownie się zalogować";
                return RedirectToAction("Login", "Home");
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View("EditCompany", vm);
                }
                else
                {

Horseplay/Views/CRM/CompanyDetails.cshtml
@model Horseplay.Models.Company
@using Horseplay.Static

    <div>
        <h4>Szczegóły firmy</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Address.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address.Street)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address.Street)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address.ZipCode)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address.ZipCode)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address.City)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address.City)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address.Country)
            </dt>

            <dd>
                <p>@Utilities.EnumString(new Horseplay.Models.Country(), (int)Model.Address.Country)</p>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactDetail.Phone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactDetail.Phone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactDetail.Mobile)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactDetail.Mobile)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactDetail.Fax)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactDetail.Fax)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactDetail.Mail)
            </dt>

            <dd>@{ var email = "mailTo:" + Model.ContactDetail.Mail; }
                <a href="@email">@Html.DisplayFor(model => model.ContactDetail.Mail)</a>
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TaxRegisterNumber)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TaxRegisterNumber)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.BusinessRegisterNumber)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.BusinessRegisterNumber)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CourtRegisterNumber)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CourtRegisterNumber)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PaymentTerm)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PaymentTerm)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>
    
            <dd>
                <p>@Utilities.EnumString(new Horseplay.Models.CompanyType(), (int)Model.Type)</p>
            </dd>

            <dt>
                @Html.Label("Dodano")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateAdded) przez użytkownika @Utilities.UserName((int)Model.AddedBy)
            </dd>
            @if (Model.DateModified != null)
            {
                <dt>
                    @Html.Label("Zmodyfikowano")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateModified) przez użytkownika @Utilities.UserName((int)Model.ModifiedBy)
                </dd>
            }

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edytuj", "EditCompany", new { id = Model.CompanyId }) |
        @Html.ActionLink("Powrót do listy firm", "GetCompanies")
    </p>

Horseplay/Views/CRM/CreateCompany.cshtml
@model Horseplay.ViewModels.CompanyViewModel

<link href="~/Content/Tab-control.css" rel="stylesheet" />

    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()

        <h4>Tworzenie firmy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <input id="tab1" type="radio" name="tabs" checked>
        <label for="tab1" class="tab-label">Ogólne</label>

        <input id="tab2" type="radio" name="tabs">
        <label for="tab2" class="tab-label">Kontakt</label>

        <input id="tab3" type="radio" name="tabs">
        <label for="tab3" class="tab-label">Finanse</label>

        

        <section id="content1">
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.Company.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Company.Type, Model.CompanyTypes(0), htmlAttributes: new { @class = "form-control company-type" })
                        @Html.ValidationMessageFor(model => model.Company.Type, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Company.Address.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.Address.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.Address.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company.Address.Street, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.Address.Street, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.Address.Street, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company.Address.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.Address.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.Address.ZipCode, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Company.Address.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.Address.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.Address.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company.Address.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Company.Address.Country, Model.Countries(0), new { @class = "form-control", id = "dd-country", data_placeholder = "Wybierz.." })
                        @Html.ValidationMessageFor(model => model.Company.Address.Country, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </section>
        <section id="content2">
            <div class="form-horizontal">
                
                <div class="form-group">
                    @Html.LabelFor(model => model.Company.ContactDetail.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.ContactDetail.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.ContactDetail.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company.ContactDetail.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.ContactDetail.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.ContactDetail.Mobile, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company.ContactDetail.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.ContactDetail.Fax, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.ContactDetail.Fax, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company.ContactDetail.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.ContactDetail.Mail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.ContactDetail.Mail, "", new { @class = "text-danger" })
                    </div>
                </div>
             </div>
        </section>
        <section id="content3">
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.Company.TaxRegisterNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.TaxRegisterNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.TaxRegisterNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company.BusinessRegisterNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.BusinessRegisterNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.BusinessRegisterNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company.CourtRegisterNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.CourtRegisterNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.CourtRegisterNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Company.PaymentTerm, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Company.PaymentTerm, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Company.PaymentTerm, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
         </section>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Utwórz" class="btn btn-default" />
                    </div>
                </div>

            }

            <div>
                @Html.ActionLink("Powrót do listy firm", "GetCompanies")
            </div>

@section scripts{
    <script>
        $(function () {
            $('#dd-country').chosen({ no_results_text: "Brak wyników dla.." });
        });
    </script>
}

Horseplay/Views/CRM/DeleteCompany.cshtml
@model Horseplay.Models.Company
@using Horseplay.Static

    <h3>Czy jesteś pewien że chcesz usunąć tę firmę?</h3>
        <div>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Address.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Address.Street)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address.Street)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Address.ZipCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address.ZipCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Address.City)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address.City)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Address.Country)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address.Country)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ContactDetail.Phone)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ContactDetail.Phone)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ContactDetail.Mobile)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ContactDetail.Mobile)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ContactDetail.Fax)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ContactDetail.Fax)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ContactDetail.Mail)
                </dt>

                <dd>
                    @{ var email = "mailTo:" + Model.ContactDetail.Mail; }
                    <a href="@email">@Html.DisplayFor(model => model.ContactDetail.Mail)</a>
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TaxRegisterNumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TaxRegisterNumber)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.BusinessRegisterNumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BusinessRegisterNumber)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CourtRegisterNumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CourtRegisterNumber)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PaymentTerm)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PaymentTerm)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Type)
                </dt>

                <dd>
                    <p>@Utilities.EnumString(new Horseplay.Models.CompanyType(), (int)Model.Type)</p>
                </dd>

                <dt>
                    @Html.Label("Dodano")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateAdded) przez użytkownika @Utilities.UserName((int)Model.AddedBy)
                </dd>

            </dl>
        </div>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model=>model.CompanyId)
            <div class="form-actions no-color">
                <input type="submit" value="Usuń" class="btn btn-danger" /> |
                @Html.ActionLink("Powrót do listy firm", "GetCompanies")
            </div>
        }

Horseplay/Views/CRM/GetCompanies.cshtml
@model IEnumerable<Horseplay.Models.Company>
@using Horseplay.Static

<link href="~/Content/table-handler.css" rel="stylesheet" />

<br />

    @if (Model != null && Model.Any())
    {
        @Html.ActionLink("Dodaj firmę", "CreateCompany");
    }
    else
    {
        HtmlString al = Html.ActionLink("Dodaj firmę", "CreateCompany", "CRM");
        string str = "Na razie nie dodałeś jeszcze żadnych firm. " + al;
        @CustomHelper.CreateGreeter(str, "red");
    }

<br/>
<section id="no-more-tables">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TaxRegisterNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BusinessRegisterNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CourtRegisterNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PaymentTerm)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td data-title="@Html.DisplayNameFor(model => model.Type)">
                            <p>@Utilities.EnumString(new Horseplay.Models.CompanyType(), (int)item.Type)</p>
                        </td>
                        <td data-title="@Html.DisplayNameFor(model => model.Address.Name)">
                            @Html.DisplayFor(modelItem => item.Address.Name)
                        </td>
                        <td data-title="@Html.DisplayNameFor(model => model.TaxRegisterNumber)">
                            @Html.DisplayFor(modelItem => item.TaxRegisterNumber)
                        </td>
                        <td data-title="@Html.DisplayNameFor(model => model.BusinessRegisterNumber)">
                            @Html.DisplayFor(modelItem => item.BusinessRegisterNumber)
                        </td>
                        <td data-title="@Html.DisplayNameFor(model => model.CourtRegisterNumber)">
                            @Html.DisplayFor(modelItem => item.CourtRegisterNumber)
                        </td>
                        <td data-title="Termin płatności">
                            @Html.DisplayFor(modelItem => item.PaymentTerm)
                        </td>
                        <td>
                            @Html.ActionLink("Edytuj", "EditCompany", new { id = item.CompanyId }) |
                            @Html.ActionLink("Szczegóły", "CompanyDetails", new { id = item.CompanyId }) |
                            @Html.ActionLink("Usuń", "DeleteCompany", new { id = item.CompanyId })
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</section>

Horseplay/Views/CRM/Index.cshtml
@using Horseplay.Static

<br />

@{
    HtmlString al = Html.ActionLink("dodać firmę", "CreateCompany", "CRM");
    string str = "Ten panel służy do zarządania relacjami z klientami, dostawcami i całym otoczeniem firmy. Portal jest ciągle rozwijany i obecna funkcjonalność różni się od ostatecznej funkcjonalności...<br><br>" + "Warto " + al;
    al = Html.ActionLink("zlecenia transportowego", "CreateTransportOrder", "Logistics");
    str += ", pozwoli to np. przypisać ją jako stronę tworzonego " + al + ".";
    al = Html.ActionLink("tutaj", "GetCompanies", "CRM");
    str += "<br>Jeśli chcesz wyświetlić listę wszystkich firm, z którymi współpracuje Twoja firma, możesz to zrobić " + al;
    @CustomHelper.CreateGreeter(str, "red");
}

<br />